import "./globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              <Link href="/">Home</Link>
              <Link href="/store">Store</Link>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
